"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/guides.html?#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""

from typing import TYPE_CHECKING

import napari
import numpy as np
from PyQt5.QtCore import Qt
from qtpy.QtWidgets import (
    QLabel,
    QLineEdit,
    QPushButton,
    QVBoxLayout,
    QHBoxLayout,
    QWidget,
    QComboBox,
    QCheckBox,
    QSpacerItem,
    QSizePolicy,)
from .widgets._processing import processing



if TYPE_CHECKING:
    import napari


# Uses the `autogenerate: true` flag in the plugin manifest
# to indicate it should be wrapped as a magicgui to autogenerate
# a widget.


class StartProcessing(QWidget):
    """
    Widget personnalisé pour traiter les données dans Napari.
    """

    def __init__(self, viewer: "napari.viewer.Viewer"):
        """
        Initialise le widget avec les boutons et les labels nécessaires.

        Parameters:
        viewer (napari.viewer.Viewer): Instance du viewer Napari.
        """
        super().__init__()
        self.viewer = viewer

        # Configuration de la mise en page principale
        self.setup_ui()


    def setup_ui(self):
        """
        Configure l'interface utilisateur
        """

        methodes_liste = ["lcs"]

        self.layout = QVBoxLayout()
        self.setLayout(self.layout)

        # Section : Résultat
        self.result_label = QLabel("Results :")
        self.layout.addWidget(self.result_label)

        # Section : Liste des layers
        btn_list_layers = QPushButton("Display list of layers :")
        btn_list_layers.clicked.connect(self.get_list_layers)
        self.layout.addWidget(btn_list_layers)

        self.layer_label = QLabel("List of layers :")
        self.layout.addWidget(self.layer_label)

        # Section : Sélection d'une tranche
        self.slice_selection_label = QLabel("Select a slice :")
        self.layout.addWidget(self.slice_selection_label)

        self.slice_selection_value = QLineEdit()
        self.layout.addWidget(self.slice_selection_value)

        btn_validate_slice = QPushButton("Confirm selection")
        btn_validate_slice.clicked.connect(self.save_value)
        self.layout.addWidget(btn_validate_slice)

        self.display_selected_slice = QLabel("No slice selected")
        self.layout.addWidget(self.display_selected_slice)

        # Section : Sélection des layers
        self.darkfield_label = QLabel("Select darkfield :")
        self.layout.addWidget(self.darkfield_label)
        self.darkfield_selection = QComboBox()
        self.layout.addWidget(self.darkfield_selection)

        self.reference_label = QLabel("Select reference :")
        self.layout.addWidget(self.reference_label)
        self.reference_selection = QComboBox()
        self.layout.addWidget(self.reference_selection)

        self.sample_label = QLabel("Select sample :")
        self.layout.addWidget(self.sample_label)
        self.sample_selection = QComboBox()
        self.layout.addWidget(self.sample_selection)

        whitefield_layout = QHBoxLayout()

        whitefield_layout.addWidget(QLabel("Flatfield :"))
        self.checkbox = QCheckBox("")
        self.checkbox.setChecked(False)
        whitefield_layout.addWidget(self.checkbox)

        self.checkbox.stateChanged.connect(lambda state: self.on_checkbox_state_changed(state, self.layout))
        self.layout.addLayout(whitefield_layout)

        self.methode_label = QLabel("Select Methode :")
        self.layout.addWidget(self.methode_label)
        self.methode_selection = QComboBox()
        self.layout.addWidget(self.methode_selection)
        self.methode_selection.addItems(methodes_liste)

        # Section : Bouton de traitement
        btn_start_processing = QPushButton("Start processing")
        btn_start_processing.clicked.connect(self.call_processing)
        self.layout.addWidget(btn_start_processing)

         # Ajouter un espace flexible pour maintenir les widgets en haut
        self.layout.addSpacerItem(QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding))

        # Placeholders pour widgets dynamiques
        self.flatfield_label = None
        self.flatfield_selection = None


    def on_checkbox_state_changed(self, checked, layout):
        """Callback pour vérifier l'état de la checkbox."""
        if checked == Qt.Checked:
            self.flatfield_label = QLabel("Select flatfield :")
            layout.addWidget(self.flatfield_label)

            self.flatfield_selection = QComboBox()
            layout.addWidget(self.flatfield_selection)

            for layer in self.viewer.layers:
                self.flatfield_selection.addItem(layer.name)

        else:
        # Supprimer les widgets dynamiques
            self.layout.removeWidget(self.flatfield_label)
            self.flatfield_label.deleteLater()
            self.flatfield_label = None

            self.layout.removeWidget(self.flatfield_selection)
            self.flatfield_selection.deleteLater()
            self.flatfield_selection = None


    def get_list_layers(self):
        """
        Affiche la liste des layers chargés dans le viewer.
        """
        if not self.viewer.layers:
            self.layer_label.setText("Aucun layer chargé.")
            return

        # Liste des noms de layers
        layer_names = [layer.name for layer in self.viewer.layers]
        self.layer_label.setText("Layers :\n" + "\n".join(layer_names))

        # Vérification des combobox avant de les utiliser
        self.darkfield_selection.clear()
        self.reference_selection.clear()
        self.sample_selection.clear()

        for layer in self.viewer.layers:
            self.darkfield_selection.addItem(layer.name)
            self.reference_selection.addItem(layer.name)
            self.sample_selection.addItem(layer.name)

    def save_value(self):
        slice_selected = self.slice_selection_value.text()
        self.display_selected_slice.setText(
            f"Selected slice: {slice_selected}"
        )
        return slice_selected


    def call_processing(self):
        """
        Appelle une fonction externe en passant les données nécessaires.
        """
        # Récupérez les données des widgets
        try:
            slice_selected = int(self.slice_selection_value.text())
        except ValueError:
            self.result_label.setText("Veuillez entrer un entier valide pour le slice.")
            return

        # Récupérer les noms des couches (layers) disponibles
        layer_names = [self.sample_selection.currentText(), self.reference_selection.currentText(), self.darkfield_selection.currentText()]

        if self.flatfield_selection is not None:
            layer_names.append(self.flatfield_selection.currentText())

        methode = self.methode_selection.currentText()

        # Vérifiez que des couches sont présentes
        if len(layer_names) < 3:  # Exemple : s'assurer d'avoir au moins 3 couches
            self.result_label.setText("Veuillez sélectionner au moins trois layers.")
            return

        # Vérifiez que le champ slice_selected est valide
        if slice_selected < 0:
            self.result_label.setText("Le numéro de slice doit être positif.")
            return

        # Affiche les informations pour débogage
        print("Couches sélectionnées :", layer_names)
        print("Slice sélectionné :", slice_selected)

        # Appel de la fonction externe avec les données
        try:
            processing(layer_names, slice_selected, self.viewer, methode)
            self.result_label.setText("Traitement terminé avec succès.")
        except Exception as e:
            self.result_label.setText(f"Erreur lors du traitement : {e}")
            print(f"Erreur : {e}")